### ISSUE TITLE
S2T2: Add unordered list of events to the homepage

### ISSUE THREAD

**Issue by altran822** [Agile-Aardvark/mgt656-spring-2015-project#9]
Add unordered list of events including their details.

**Comment by alijoseph** [comment]
Grading Note: each event is in an li element with class="event" and id="event-{id}", where {id} indicates the numerical id of the event. E.g. your event list may look something like the following:

  <ul>
    <li class="event" id="event-1">...</li>
    <li class="event" id="event-2">...</li>
  </ul>
